### ISSUE TITLE
Pipewire default/example configuration is incorrect

### ISSUE THREAD

**Issue by rp86** [HEnquist/camilladsp-config#1]
Hi, there is a minor error in the example pipewire configuration:
api.alsa.path = "hw:Loopback,1,0" 

should instead be:
api.alsa.path = "hw:Loopback,0,0"

to send audio to the 'sink' end of the ALSA loopback device. 

Thanks!

**Comment by HEnquist** [comment]
Thanks for reporting! I'll fix it asap.

**Comment by Quickmcj** [comment]
This can be closed with #2
